# Generated by Django 4.1.7 on 2023-03-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uniqueid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField(default='00:00:00')),
                ('uniqueid', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, default=123, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogTable.user')),
            ],
        ),
    ]
