# Generated by Django 4.1.7 on 2023-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0004_alter_logstable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
