# Generated by Django 4.1.7 on 2023-03-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0005_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='user',
            field=models.ForeignKey(blank=True, default=123, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='LogTable.user'),
        ),
    ]
