# Generated by Django 4.1.7 on 2023-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0006_roles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
