# Generated by Django 4.1.7 on 2023-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0011_alter_logstable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
