# Generated by Django 4.1.7 on 2023-03-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0015_remove_user_roles_roles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_namescc', to='LogTable.user'),
        ),
    ]
