# Generated by Django 4.1.7 on 2023-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0017_alter_roles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='uniqueid',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='LogTable.roles'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'manager'), (2, 'employee'), (3, 'admin'), (4, 'supervisor')], primary_key=True, serialize=False),
        ),
    ]
