# Generated by Django 4.1.7 on 2023-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0018_remove_roles_role_remove_roles_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
