# Generated by Django 4.1.7 on 2023-03-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogTable', '0019_alter_roles_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='id',
            new_name='role',
        ),
    ]
