# Generated by Django 4.1.7 on 2023-03-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_logtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='user',
            new_name='userid',
        ),
    ]
