# Generated by Django 4.1.7 on 2023-03-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_user_logtable_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogTable',
            new_name='Table',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='userid',
            new_name='uniqueid',
        ),
    ]
