# Generated by Django 4.1.7 on 2023-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_rename_logtable_table_rename_userid_table_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
