# Generated by Django 4.1.7 on 2023-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_table_day_alter_table_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time_out',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
