# Generated by Django 4.1.7 on 2023-03-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_table_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='uniqueid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
