# Generated by Django 4.1.7 on 2023-03-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_table_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField(default='00:00:00')),
                ('uniqueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.user')),
            ],
        ),
    ]
