# Generated by Django 4.1.7 on 2023-03-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_logstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='table',
            name='uniqueid',
        ),
        migrations.DeleteModel(
            name='idenetityModel',
        ),
        migrations.DeleteModel(
            name='logs',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
