# Generated by Django 4.1.7 on 2023-03-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_logstable_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstable',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
