# Generated by Django 4.1.7 on 2023-03-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_alter_logstable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstable',
            name='user',
        ),
    ]
