# Generated by Django 4.1.7 on 2023-03-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_remove_logstable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
