# Generated by Django 4.1.7 on 2023-03-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_logstable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logstable',
            old_name='user',
            new_name='logs',
        ),
    ]
