# Generated by Django 4.1.7 on 2023-03-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0021_rename_user_logstable_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logstable',
            old_name='logs',
            new_name='user',
        ),
    ]
