# Generated by Django 4.1.7 on 2023-03-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0022_rename_logs_logstable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstable',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='logs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logs.logstable'),
            preserve_default=False,
        ),
    ]
