# Generated by Django 4.1.7 on 2023-03-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0023_remove_logstable_user_user_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logs',
        ),
        migrations.AddField(
            model_name='logstable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
