# Generated by Django 4.1.7 on 2023-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0035_alter_logstable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
