# Generated by Django 4.1.7 on 2023-03-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0042_user_id_alter_user_uniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logstable',
            old_name='user',
            new_name='logs',
        ),
    ]
