# Generated by Django 4.1.7 on 2023-03-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0045_alter_logstable_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logstable',
            name='logs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logs.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
