# Generated by Django 4.1.7 on 2023-03-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0046_user_id_alter_logstable_logs_alter_user_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstable',
            name='logs',
        ),
        migrations.AddField(
            model_name='logstable',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
