# Generated by Django 4.1.7 on 2023-03-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0049_remove_user_id_alter_user_uniqueid_logstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstable',
            name='user',
            field=models.ForeignKey(blank=True, default='id', null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.user'),
        ),
    ]
